pipeline {
  agent any

  stages {
    stage ('Initial clean up') {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('package') {
      steps {
        script {
          sh 'echo "Packaging App'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploying to Dev"'
        }
      }
    }

    stage('Clean') {
      steps {
        script {
          sh 'echo "clean up"'
        }
      }
    }
  }
}
    